# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c679f3d41e398bd25dd8e45d0a1bcf4b870f7260248237beedaebca13700333dae1a87f2859f07c2c45d2c42e2b1187dd0f7c56dc0dbf06ea151824a1fa3e634

test:
  secret_key_base: 834f67bacef92488d3a87fecd6fcbac6ae16544c86bcda5018ab75ec87704b83170d2b459496a203c2ca40d63f4d6ad6965bdb486c11e8c1ff91f91965b339da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: c679f3d41e398bd25dd8e45d0a1bcf4b870f7260248237beedaebca13700333dae1a87f2859f07c2c45d2c42e2b1187dd0f7c56dc0dbf06ea151824a1fa3e634
